config/routes.rb
Rails.application.routes.draw do
  root 'tickets#new'

  get   '/dashboard',             to: 'dashboard#index'
  get   '/staffs/sign_up',        to: 'signups#new'
  post  '/staffs/sign_up',        to: 'signups#create'
  post  '/',                      to: 'tickets#create'
  post  '/tickets/assign',        to: 'tickets#assign'
  post  '/reply',                 to: 'tickets#reply'
  post  '/question',              to: 'tickets#question'
  get   '/tickets/status/change', to: 'tickets#change_status'
  get   '/tickets/department/change', to: 'tickets#change_department'
  get   '/myticket',              to: 'tickets#myticket'
  get   '/activitylogs',          to: 'tickets#activitylogs'
  get   '/tickets/search',        to: 'dashboard#search'
  get   'departments/new',        to: 'departments#new'
  post  'departments/new',        to: 'departments#create'

  resources :tickets, only: [:show, :new, :create]
  devise_for :staffs, controllers: { sessions:      'staffs/sessions',
                                     passwords:     'staffs/passwords' }
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Kaminari::Helpers::HelperMethods

  before_action :signed_in?, only: [:index, :search]

  def index
    @unassigneds = Ticket.unassigneds(current_staff.department).page(params[:unassigneds_page])
    @opens = Ticket.opens(current_staff).page(params[:opens_page])
    @onholds = Ticket.onholds(current_staff).page(params[:onholds_page])
    @closeds = Ticket.closeds(current_staff).page(params[:cloaseds_page])
  end

  def search
    @searcheds = Ticket.search(current_staff, params[:search], current_staff.department)
                 .page(params[:page])

    # tickets_rendered = '<div class="tickets">' + render_to_string(@searcheds) + '</div>'
    # pagination_rendered = paginate @searcheds
    respond_to do |format|
      format.js { render layout: false }
    end
  end
end

app/views/dashboard/_searcheds.html.haml
%div.mt-3.ml-5
  = paginate @searcheds, :remote => true if @searcheds
%div.tickets
  %table.table.table-sm
    = render @searcheds if @searcheds
%div.mt-3.ml-5
  = paginate @searcheds, :remote => true if @searcheds

app/views/dashboard/index.html.haml
%div.card
  %div.card-header.pb-0
    %div.float-right.pb-1
      =form_tag tickets_search_path, method: :get, remote: true, id: 'search_form' do
        %input.form-control.float-right{type: 'text', placeholder: 'Number/Subject ...', id: 'search_input', name: 'search', onkeyup: "$('#search_form').submit()" }
    %ul.nav.nav-tabs.card-header-tabs
      %li.nav-item
        %a.nav-link.active{id: 'unassigned-tab', 'data-toggle': 'tab', href: '#unassigned', role:'tab', 'aria-controls': 'unassigned', 'aria-selected': 'false'}= 'Unassigned'
      %li.nav-item
        %a.nav-link{id: 'open-tab', 'data-toggle': 'tab', href: '#open', role:'tab', 'aria-controls': 'open', 'aria-selected': 'false'}= 'Open'
      %li.nav-item
        %a.nav-link{id: 'onhold-tab', 'data-toggle': 'tab', href: '#onhold', role:'tab', 'aria-controls': 'onhold', 'aria-selected': 'false'}= 'On hold'
      %li.nav-item
        %a.nav-link{id: 'closed-tab', 'data-toggle': 'tab', href: '#closed', role:'tab', 'aria-controls': 'closed', 'aria-selected': 'false'}= 'Closed'
      %li.tab-pane.fade{id: 'search'}
        %btn.nav-link.btn-light.fade{id: 'search_btn'}= 'Search'
  %div.car-body
    %div.tab-content{id: 'myTabContent'}
      %div.tab-pane.fade.show.active{id: 'unassigned', role: 'tabpanel', 'aria-labelledby': 'unassigned-tab'}
        %div.mt-3.ml-5
          = paginate @unassigneds, param_name: "unassigneds_page"
        %div.tickets
          %table.table.table-sm
            = render @unassigneds
        %div.mt-3.ml-5
          = paginate @unassigneds, param_name: "unassigneds_page"
      %div.tab-pane.fade{id: 'open', role: 'tabpanel', 'aria-labelledby': 'open-tab'}
        %div.mt-3.ml-5
          = paginate @opens, param_name: "opens_page"
        %div.tickets
          %table.table.table-sm
            = render @opens
        %div.mt-3.ml-5
          = paginate @opens, param_name: "opens_page"
      %div.tab-pane.fade{id: 'onhold', role: 'tabpanel', 'aria-labelledby': 'onhold-tab'}
        %div.mt-3.ml-5
          = paginate @onholds, param_name: "onholds_page"
        %div.tickets
          %table.table.table-sm
            = render @onholds
        %div.mt-3.ml-5
          = paginate @onholds, param_name: "onholds_page"
      %div.tab-pane.fade{id: 'closed', role: 'tabpanel', 'aria-labelledby': 'closed-tab'}
        %div.mt-3.ml-5
          = paginate @closeds, param_name: "closeds_page"
        %div.tickets
          %table.table.table-sm
            = render @closeds
        %div.mt-3.ml-5
          = paginate @closeds, param_name: "closeds_page"

      %div.tab-pane.fade{id: 'search_div', role: 'tabpanel', 'aria-labelledby': 'search-tab'}
        = render 'searcheds'

app/views/dashboard/search.js.erb
$('#search_div').html("<%= j render(:partial => 'dashboard/searcheds') %>");
$('#search_div').addClass("show active");
$('#search').addClass("show active");
$('#search_btn').addClass("show active");
$('#unassigned').removeClass("show active");
$('#open').removeClass("show active");
$('#onhold').removeClass("show active");
$('#closed').removeClass("show active");
$('#unassigned-tab').removeClass("active");
$('#open-tab').removeClass("active");
$('#onhold-tab').removeClass("active");
$('#closed-tab').removeClass("active");