config/routes.rb
Rails.application.routes.draw do
  root 'tickets#new'

  get   '/dashboard',             to: 'dashboard#index'
  get   '/staffs/sign_up',        to: 'signups#new'
  post  '/staffs/sign_up',        to: 'signups#create'
  post  '/',                      to: 'tickets#create'
  post  '/tickets/assign',        to: 'tickets#assign'
  post  '/reply',                 to: 'tickets#reply'
  post  '/question',              to: 'tickets#question'
  get   '/tickets/status/change', to: 'tickets#change_status'
  get   '/tickets/department/change', to: 'tickets#change_department'
  get   '/myticket',              to: 'tickets#myticket'
  get   '/activitylogs',          to: 'tickets#activitylogs'
  get   '/tickets/search',        to: 'dashboard#search'
  get   'departments/new',        to: 'departments#new'
  post  'departments/new',        to: 'departments#create'

  resources :tickets, only: [:show, :new, :create]
  devise_for :staffs, controllers: { sessions:      'staffs/sessions',
                                     passwords:     'staffs/passwords' }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :client
  belongs_to :status
  belongs_to :staff, optional: true
  belongs_to :department
  has_many :comments
  has_many :activity_logs

  accepts_nested_attributes_for :comments

  scope :unassigneds, -> (department) { where(status: 1,
                                              department: department)
                                        .includes(:status) }
  scope :opens, -> (current_staff) { where(status: 2,
                                           staff: current_staff)
                                     .order(:updated_at)
                                     .includes(:status) }
  scope :onholds, -> (current_staff) { where(status: 3,
                                             staff: current_staff)
                                       .order(:updated_at)
                                       .includes(:status) }
  scope :closeds, -> (current_staff) { where(status: 4,
                                             staff: current_staff)
                                       .order(:updated_at)
                                       .includes(:status) }
  scope :search, -> (current_staff,
                      search,
                      department) { where(staff: current_staff)
                                    .or(where(status: 1,
                                              department: department))
                                    .where("lower(number) LIKE ? OR lower(subject) LIKE ?",
                                           "%#{search.downcase}%", "%#{search.downcase}%")
                                    .order(:updated_at)
                                    .includes(:status) }

  before_create :generate_link
  before_create :inc_number

  validates :subject, presence: true, length: { minimum: 6,
                                                maximum: 48 }

  private
    def generate_link
      self.link = SecureRandom.urlsafe_base64
    end

    def inc_number
      number = Ticket.last ? Ticket.last.number : 'AAA-00-AAA-00-AAA'
      def increment(src)
        if src.length == 2
          src = (src.to_i(16).next % 256).to_s(16).upcase.rjust(2,'0')
        else
          src = src.next
          src = 'AAA' if src == 'AAAA'
        end
        src
      end

      s_t_1 = number[0..2]
      s_h_1 = number[4..5]
      s_t_2 = number[7..9]
      s_h_2 = number[11..12]
      s_t_3 = number[14..16]

      t_s_t_1 = s_t_1
      t_s_h_1 = s_h_1
      t_s_t_2 = s_t_2
      t_s_h_2 = s_h_2
      t_s_t_3 = s_t_3

      s_t_3 = increment(s_t_3)
      s_h_2 = increment(s_h_2) if s_t_3 < t_s_t_3
      s_t_2 = increment(s_t_2) if s_h_2 < t_s_h_2
      s_h_1 = increment(s_h_1) if s_t_2 < t_s_t_2
      s_t_1 = increment(s_t_1) if s_h_1 < t_s_h_1

      self.number = s_t_1 + '-' + s_h_1 + '-' + s_t_2 + '-' + s_h_2 + '-' + s_t_3
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :signed_in?, only: [:show, :assign, :change_status, :change_department]
  before_action :get_ticket, only: [:show, :assign, :change_status, :change_department, :reply]
  before_action :get_ticket_by_link, only: [:myticket, :question]
  before_action :get_client, only: [:show, :myticket, :question]
  before_action :get_comments, only: [:show, :myticket]

  def show
    @status = Status.new
    @comment = Comment.new
    @department = Department.new
  end

  def myticket
    @comment = Comment.new
  end

  def new
    @ticket = Ticket.new
    @client = Client.new
    ticket = @client.tickets.build
    comment = ticket.comments.build
    @comment = Comment.new
    @department = Department.new
  end

  def create
    @department = Department.find(department_params)
    @client = Client.find_by(email: client_params[:email].downcase)
    if @client
      @client.tickets.build(ticket_params)
    else
      @client = Client.new(client_params)
    end
    @client.email.downcase!
    @client.tickets.last.department = @department
    @client.tickets.last.comments[0].author = @client

    if @client.save
      flash[:notice] = 'Ticket created'
      @client.tickets.last.activity_logs.create(activity: 'Ticket was created')
      ClientMailer.ticket_created(@client.tickets[0]).deliver
      redirect_to root_path
    else
      render 'new'
    end
  end

  def assign
    @ticket.update(staff: current_staff, status_id: 2)
    @ticket.activity_logs.create(activity: 'Ticket was assigned by ' + @ticket.staff.email)
    redirect_to @ticket
    ClientMailer.ticket_status(@ticket).deliver
  end

  def change_status
    status_before = @ticket.status
    @ticket.staff_id = nil if params[:status_id] == 1
    @ticket.update(status_id: params[:status_id])
    @ticket.activity_logs.create(activity: 'Ticket changed status from ' + status_before.name + ' to status ' + @ticket.status.name)
    ClientMailer.ticket_status(@ticket).deliver
  end

  def change_department
    department_before = @ticket.department
    @ticket.update(department_id: params[:department_id])
    @ticket.activity_logs.create(activity: 'Ticket moved from ' + department_before.name + ' to ' + @ticket.department.name + ' department')
    ClientMailer.ticket_department(@ticket).deliver
  end

  def reply
    @comment = Comment.new(reply_params)
    @comment.update(author: current_staff, ticket: @ticket)
    flash[:notice] = 'Replyed!'
    @ticket.activity_logs.create(activity: @ticket.staff.email + ' replied')
    ClientMailer.ticket_replied(@ticket).deliver
    redirect_to @ticket
  end

  def question
    @comment = Comment.new(reply_params)
    @comment.update(author: @client, ticket: @ticket)
    flash[:notice] = 'Replyed!'
    @ticket.activity_logs.create(activity: @ticket.client.name + ' replied')
    redirect_to myticket_path(link: @ticket.link)
  end

  def activitylogs
    @logs = ActivityLog.where(ticket_id: params[:id]).page(params[:page])
  end

  private
    def client_params
      params.require(:client)
            .permit(:name, :email,
                     tickets_attributes: [:subject,
                                           comments_attributes: [:message]
                                         ])
    end

    def comment_params
      params.require(:ticket).require(:comment).permit(:message)
    end

    def reply_params
      params.require(:comment).permit(:message)
    end

    def ticket_params
      params.require(:client)
            .require(:tickets_attributes)
            .require('0')
            .permit(:subject,
                      comments_attributes: [:message]
                    )
    end

    def department_params
      params.require(:client).require(:department).permit(:id)[:id]
    end

    def get_ticket
      @ticket = Ticket.find(params[:id])
    end

    def get_ticket_by_link
      @ticket = Ticket.find_by(link: params[:link])
    end

    def get_client
      @client = @ticket.client
    end

    def get_comments
      @comments = Comment.where(ticket: @ticket).includes(:author)
                                                .order(:created_at)
                                                .page(params[:page])
    end
end

app/views/tickets/_ticket.html.haml
%tr
  %td
    %span{class: ticket.status.name.downcase.delete(' ')}
  %td.w-75=link_to "(#{ticket.number}) #{ticket.subject}", ticket, id: ticket.id
  %td.w-100.text-right=ticket.updated_at

app/views/tickets/activitylogs.html.haml
%div.container
  = paginate @logs
  %ul.tickets= render @logs
  = paginate @logs

app/views/tickets/myticket.html.haml
%div.container
  %table.w-100
    %tr
      %td.w-50
        = @client.name
        %br
        = @client.email
      %td.w-25.font-weight-bold.h3
        = @ticket.status.name
    %tr
      %td.pt-4.font-weight-bold{colspan: 3}
        %span.d-flex.justify-content-center.h3
          = @ticket.number
    %tr
      %td.font-weight-bold{colspan: 3}
        %span.d-flex.justify-content-center.h1
          = link_to @ticket.subject, activitylogs_path(id: @ticket.id)
    %tr
      %td{colspan: 3}
        = paginate @comments
        = render @comments
    %tr
      %td.pt-5{colspan: 3}
        - if @ticket.status_id != 1 && @ticket.status_id != 4
          = form_for(@comment, url: question_path(link: @ticket.link)) do |f|
            = f.label :message
            = f.text_area :message, class: 'form-control'

            = f.submit 'Send!', class: 'form-control'

app/views/tickets/new.html.haml
%h1= 'Create new ticket'

%div.row
  %div.col-md-6.col-md-offset-3
    = form_for(@client, url: root_path) do |f|
      = render 'shared/error_tickets_messages'
      %div.form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', id: 'ticket_name'
      %div.form-group
        = f.label :email
        = f.email_field :email, class: 'form-control', id: 'ticket_email'
      = f.fields_for :tickets do |ff|
        %div.form-group
          = ff.label :subject
          = ff.text_field :subject, class: 'form-control', id: 'ticket_subject'
        = ff.fields_for :comments do |fff|
          %div.form-group
            = fff.label :message
            = fff.text_area :message, class: 'form-control', id: 'ticket_message'
      = f.fields_for @department do |ff|
        %div.form-group
          = ff.collection_select :id, Department.order(:id), :id, :name, {}, { class: 'custom-select' }
      %div.actions
        = f.submit 'Create new ticket', class: 'btn btn-success'

app/views/tickets/show.html.haml
%div.container
  %table.w-100
    %tr
      %td.w-50
        = @client.name
        %br
        = @client.email
      %td.w-25.h4
        - if @ticket.status.id == 1
          = link_to 'Get ticket!', tickets_assign_path(id: @ticket.id), method: :post
          = form_for(@department, url: tickets_status_change_path) do |f|
            = f.collection_select :id, Department.order(:id), :id, :name, { selected: @ticket.department.id }, { class: 'custom-select', 'data-ticket': @ticket.id, 'data-selected': @department.id, 'data-path': ticket_path(@ticket.id) }
        - else
          = form_for(@status, url: tickets_status_change_path) do |f|
            = f.collection_select :id, Status.order(:id), :id, :name, { selected: @ticket.status.id }, { class: 'custom-select', 'data-selected': @ticket.id, 'data-path': ticket_path(@ticket.id) }
    %tr
      %td.pt-4.font-weight-bold{colspan: 3}
        %span.d-flex.justify-content-center.h3
          = @ticket.number
    %tr
      %td.font-weight-bold{colspan: 3}
        %span.d-flex.justify-content-center.h1
          = link_to @ticket.subject, activitylogs_path(id: @ticket.id)
    %tr
      %td{colspan: 3}
        = paginate @comments
        = render @comments
    %tr
      %td.pt-5{colspan: 3}
        - if @ticket.status_id != 1 && @ticket.status_id != 4
          = form_for(@comment, url: reply_path(id: @ticket.id)) do |f|
            = f.label :message
            = f.text_area :message, class: 'form-control'

            = f.submit 'Send!', class: 'form-control'