config/routes.rb
Rails.application.routes.draw do
  root 'tickets#new'

  get   '/dashboard',             to: 'dashboard#index'
  get   '/staffs/sign_up',        to: 'signups#new'
  post  '/staffs/sign_up',        to: 'signups#create'
  post  '/',                      to: 'tickets#create'
  post  '/tickets/assign',        to: 'tickets#assign'
  post  '/reply',                 to: 'tickets#reply'
  post  '/question',              to: 'tickets#question'
  get   '/tickets/status/change', to: 'tickets#change_status'
  get   '/tickets/department/change', to: 'tickets#change_department'
  get   '/myticket',              to: 'tickets#myticket'
  get   '/activitylogs',          to: 'tickets#activitylogs'
  get   '/tickets/search',        to: 'dashboard#search'
  get   'departments/new',        to: 'departments#new'
  post  'departments/new',        to: 'departments#create'

  resources :tickets, only: [:show, :new, :create]
  devise_for :staffs, controllers: { sessions:      'staffs/sessions',
                                     passwords:     'staffs/passwords' }
end

app/views/layouts/_header.html.haml
%header.pb-4
  %nav.navbar.navbar-dark.bg-dark
    - if staff_signed_in?
      = link_to 'TICKETS', dashboard_path, id: 'logo'
    - else
      = link_to 'TICKETS', root_path, id: 'logo'
    %ul.nav
      - if staff_signed_in?
        %label.username.mr-5.pr-5
          = "#{current_staff.email}(#{current_staff.department.name})"
        - if current_staff.admin?
          %li.nav-item
            = link_to 'Create staff', staffs_sign_up_path , class: 'btn btn-dark', id: 'create_new_staff'
          %li.nav-item
            = link_to 'Create department', departments_new_path , class: 'btn btn-dark', id: 'create_new_department'
        %li.nav-item
          = link_to 'Log out', destroy_staff_session_path, method: :delete , class: 'btn btn-dark'
      - else 
        %li.nav-item
          = link_to 'Log in', new_staff_session_path, class: 'btn btn-dark'

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= csp_meta_tag

= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= 'TicketSystem'
    = render 'layouts/rails_default'

  %body
    = render 'layouts/header'

    %div.container
      - if notice
        %p.alert.alert-success
          = notice
      - if alert
        %p.alert.alert-danger
          = alert
      = yield